from pydantic import BaseModel, Field
from .msg import MsgResponse
from enum import Enum
from .link import LinkType


class ScoreType(str, Enum):
    POSITIVE = "positive"
    NEGATIVE = "negative"


class LogicType(str, Enum):
    OR = "or"
    AND = "and"


class CreateOrOpinionRequest(BaseModel):
    content: str = Field(..., description="The content of the opinion", min_length=1)
    creator: str = Field(
        ..., description="ID of the user creating the opinion", min_length=1
    )
    positive_score: float | None = None
    is_llm_score: bool = Field(
        False, description="Whether the score is generated by an LLM"
    )
    debate_id: str | None = Field(
        None, description="ID of the debate this opinion belongs to"
    )


class CreateAndOpinionRequest(BaseModel):
    parent_id: str = Field(..., description="ID of the parent opinion", min_length=1)
    son_ids: list[str] = Field(
        ..., description="List of IDs of the child opinions",
    )
    link_type: LinkType = Field(
        ..., description="Type of link to create between the parent and child opinions"
    )
    creator: str = Field(
        ..., description="ID of the user creating the opinion", min_length=1
    )
    debate_id: str | None = Field(
        None, description="ID of the debate this opinion belongs to"
    )


class DeleteOpinionRequest(BaseModel):
    opinion_id: str
    debate_id: str | None = None


class InfoOpinionRequest(BaseModel):
    opinion_id: str
    debate_id: str | None = None


class InfoOpinionResponse(MsgResponse):
    data: dict | None = Field(None, description="Details of the opinion if found")


class QueryOpinionRequest(BaseModel):
    q: str | None = None
    debate_id: str | None = None
    min_score: float | None = None
    max_score: float | None = None


class QueryOpinionResponse(MsgResponse):
    data: list[dict] | None = Field(
        None, description="Opinions matching the query parameters"
    )


class PatchOpinionRequest(BaseModel):
    id: str
    content: str | None = None
    score: float | None = None
    is_llm_score: bool = Field(
        False, description="Whether the score is generated by an LLM"
    )
    creator: str | None = None
